version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
